"""Clustering pipeline, naming, and supporting models."""

from .api import (
    ALL_NOISE_DISTANCE_THRESHOLD,
    CLUSTER_NAME_CONTENT_LIMIT,
    CLUSTER_NAME_EXCERPT_LIMIT,
    CLUSTER_NAME_OUTPUT_LIMIT,
    KNN_DYNAMIC_THRESHOLD_MULTIPLIER,
    _build_cluster_debug_labels,
    _build_cluster_naming_prompt,
    _cluster_debug_token,
    _compact_sample_for_naming,
    _extract_title_like_line,
    _looks_like_author_line,
    cluster_documents,
    generate_all_cluster_names,
    generate_cluster_name,
    merge_clusters_by_name,
    merge_small_clusters_by_similarity,
    repair_noise_with_knn,
)
from .link import build_candidate_components, build_candidate_edges
from .model import (
    AdjudicationDecision,
    AdjudicationRequest,
    CandidateComponent,
    CandidateEdge,
    ClusterMetrics,
    ClusterRepresentation,
    ClusterResult,
    SmallClusterMergeEvent,
    SmallClusterSkipEvent,
)
from .rule import (
    apply_rule_adjudication,
    build_adjudication_requests,
)

__all__ = [
    "ALL_NOISE_DISTANCE_THRESHOLD",
    "CLUSTER_NAME_CONTENT_LIMIT",
    "CLUSTER_NAME_EXCERPT_LIMIT",
    "CLUSTER_NAME_OUTPUT_LIMIT",
    "KNN_DYNAMIC_THRESHOLD_MULTIPLIER",
    "_build_cluster_debug_labels",
    "_build_cluster_naming_prompt",
    "_cluster_debug_token",
    "_compact_sample_for_naming",
    "_extract_title_like_line",
    "_looks_like_author_line",
    "cluster_documents",
    "generate_all_cluster_names",
    "generate_cluster_name",
    "merge_clusters_by_name",
    "merge_small_clusters_by_similarity",
    "repair_noise_with_knn",
    "ClusterMetrics",
    "ClusterRepresentation",
    "ClusterResult",
    "SmallClusterMergeEvent",
    "SmallClusterSkipEvent",
    "CandidateComponent",
    "CandidateEdge",
    "AdjudicationDecision",
    "AdjudicationRequest",
    "apply_rule_adjudication",
    "build_adjudication_requests",
    "build_candidate_components",
    "build_candidate_edges",
]
